name: 'NATS Test'
description: 'Tests API behavior with NATS'
inputs:
  topic:
    description: 'Topic to send message'
    required: true
  message:
    description: 'Message'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - "${{ inputs.topic}}"
    - "${{ inputs.message}}"
