name: 'Dotnet Setup'
description: 'Setups the desired dotnet version, restores the project and returns the build version'
inputs:
  dotNetVersion:
    description: 'Desired dotnet version to setup'
    required: true
outputs:
  version:
    description: 'Build version that will be used by the application'
runs:
  using: 'composite'
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{inputs.dotNetVersion}}

    - name: Restore dependencies
      run: dotnet restore
      shell: bash

    - name: Set version
      id: setVersion
      run: echo "::set-output name=version::0.${{github.run_number}}.0"
      shell: bash